### ISSUE TITLE
'undefined' is not an object! (line undefined)

### ISSUE THREAD

**Issue by Rendaman13** [ISSOtm/gbz80-to-items#13]
It didn't give me a line, so I'll just post the whole code:

Ld c,$00
start:
 Call $3ffa
 Ldh a,($b2)
 Cp $10
 jr z,left
 Cp $20
 Jr z,right
 Ldh a,($f8)
 Cp $02
 jr z,end
 Jr start
left:
 Dec c
 Jr start
right:
 inc c
 Jr start
end:
 ld b,c
 ld c,$64
 call $3e48
 ret

**Comment by ISSOtm** [comment]
This code produced an error for me, but not this one.
I'll fix this new error, maybe it'll fix this one ?

**Comment by ISSOtm** [comment]
The reason why this happened was that AND, OR, XOR and CP had broken functions that didn't return a length. This, in itself, doesn't break anything, but then (after assembling) the labels get assigned "NaN" as their offset. Then everything blew up at linking time.
